In [2]:
# Assignment 1 - Working with NumPy
# Import NumPy
import numpy as np

# Step 1: Create a 1D NumPy array with integers from 1 to 20
arr1 = np.arange(1, 21)
print("1D Array:", arr1)
# a. Calculate sum, mean, median, and standard deviation
sum_arr1 = np.sum(arr1)
mean_arr1 = np.mean(arr1)
median_arr1 = np.median(arr1)
std_arr1 = np.std(arr1)
print(f"Sum: {sum_arr1}, Mean: {mean_arr1}, Median: {median_arr1}, Std Dev: {std_arr1}")
# b. Find indices of elements greater than 10
indices_gt_10 = np.where(arr1 > 10)[0]
print("Indices of elements > 10:", indices_gt_10)
# Step 2: Create a 2D NumPy array of shape 4x4 with numbers from 1 to 16
arr2 = np.arange(1, 17).reshape(4, 4)
print("\n2D Array (4x4):")
print(arr2)
# b. Transpose
transpose_arr2 = arr2.T
print("\nTranspose:")
print(transpose_arr2)
# c. Row-wise and column-wise sums
row_sums = np.sum(arr2, axis=1)
col_sums = np.sum(arr2, axis=0)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)

# Step 3: Create two 3x3 arrays with random integers between 1 and 20
arr3a = np.random.randint(1, 21, (3, 3))
arr3b = np.random.randint(1, 21, (3, 3))
print("\nArray 3A:")
print(arr3a)
print("\nArray 3B:")
print(arr3b)
# a. Element-wise operations
add_result = arr3a + arr3b
sub_result = arr3a - arr3b
mul_result = arr3a * arr3b
print("\nElement-wise Addition:")
print(add_result)
print("\nElement-wise Subtraction:")
print(sub_result)
print("\nElement-wise Multiplication:")
print(mul_result)
# b. Dot product
dot_product = np.dot(arr3a, arr3b)
print("\nDot Product:")
print(dot_product)

# Step 4: Reshape a 1D array of size 12 into 3x4 and slice first two rows and last two columns
arr4 = np.arange(12)
reshaped_arr4 = arr4.reshape(3, 4)
print("\nOriginal 1D Array:", arr4)
print("Reshaped to 3x4:")
print(reshaped_arr4)
# Slice first two rows and last two columns
sliced = reshaped_arr4[:2, -2:]
print("\nSliced (first two rows, last two columns):")
print(sliced)

1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210, Mean: 10.5, Median: 10.5, Std Dev: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]

2D Array (4x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose:
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]

Array 3A:
[[11 19 20]
 [17  7  6]
 [20  8  8]]

Array 3B:
[[15 16 17]
 [11 17  6]
 [17  5  2]]

Element-wise Addition:
[[26 35 37]
 [28 24 12]
 [37 13 10]]

Element-wise Subtraction:
[[ -4   3   3]
 [  6 -10   0]
 [  3   3   6]]

Element-wise Multiplication:
[[165 304 340]
 [187 119  36]
 [340  40  16]]

Dot Product:
[[714 599 341]
 [434 421 343]
 [524 496 404]]

Original 1D Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Sliced (first two rows, last two columns):
[[2 3]
 [6 7]]
